spring:
  application:
    name: eureka-server
  profiles:
    active: local

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    
management:
  endpoints:
    web:
      exposure:
        include: '*'